import { NextResponse } from "next/server";
import crypto from "crypto";
import { createClient } from "@supabase/supabase-js";

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY
);

export async function POST(request) {
  try {
    // ----------------------------------------------------------
    // 1. Receive PayFast notification
    // ----------------------------------------------------------

    const rawBody = await request.text();

    const params = new URLSearchParams(rawBody);

    const receivedSignature =
      params.get("signature");

    if (!receivedSignature) {
      return new NextResponse(
        "Missing signature",
        { status: 400 }
      );
    }

    // ----------------------------------------------------------
    // 2. Rebuild the PayFast signature
    // ----------------------------------------------------------

    const paymentData = {};

    for (const [key, value] of params.entries()) {
      if (key !== "signature") {
        paymentData[key] = value;
      }
    }

    const signatureString = Object.entries(
      paymentData
    )
      .filter(
        ([key, value]) =>
          value !== undefined &&
          value !== null &&
          value !== ""
      )
      .map(
        ([key, value]) =>
          `${key}=${encodeURIComponent(
            String(value).trim()
          )}`
      )
      .join("&");

    const passphrase =
      process.env.PAYFAST_PASSPHRASE;

    const stringToHash = passphrase
      ? `${signatureString}&passphrase=${encodeURIComponent(
          passphrase.trim()
        )}`
      : signatureString;

    const calculatedSignature =
      crypto
        .createHash("md5")
        .update(stringToHash)
        .digest("hex");

    // ----------------------------------------------------------
    // 3. Compare signatures
    // ----------------------------------------------------------

    if (
      calculatedSignature !==
      receivedSignature
    ) {
      console.error(
        "PayFast signature verification failed."
      );

      return new NextResponse(
        "Invalid signature",
        { status: 400 }
      );
    }

    // ----------------------------------------------------------
    // 4. Read payment information
    // ----------------------------------------------------------

    const paymentStatus =
      params.get("payment_status");

    const merchantId =
      params.get("merchant_id");

    const paymentId =
      params.get("m_payment_id");

    const amountGross =
      params.get("amount_gross");

    const emailAddress =
      params.get("email_address");

    const itemName =
      params.get("item_name");

    // ----------------------------------------------------------
    // 5. Verify merchant ID
    // ----------------------------------------------------------

    if (
      merchantId !==
      process.env.PAYFAST_MERCHANT_ID
    ) {
      console.error(
        "PayFast merchant ID mismatch."
      );

      return new NextResponse(
        "Invalid merchant",
        { status: 400 }
      );
    }

    // ----------------------------------------------------------
    // 6. Only successful payments can activate
    // ----------------------------------------------------------

    if (paymentStatus !== "COMPLETE") {
      console.log(
        "PayFast payment not complete:",
        paymentStatus
      );

      return new NextResponse("OK", {
        status: 200,
      });
    }

    // ----------------------------------------------------------
    // 7. Find the subscription
    // ----------------------------------------------------------

    /*
     * Our payment ID is generated by create-payment
     * in this format:
     *
     * GL-xxxxxxxxxxxxx
     *
     * The company subscription was created as
     * inactive before PayFast checkout.
     */

    if (!paymentId) {
      return new NextResponse(
        "Missing payment ID",
        { status: 400 }
      );
    }

    /*
     * Extract the timestamp from:
     *
     * GL-1750000000000
     */

    const timestamp =
      paymentId.replace("GL-", "");

    if (!timestamp) {
      return new NextResponse(
        "Invalid payment ID",
        { status: 400 }
      );
    }

    // ----------------------------------------------------------
    // 8. Find recent inactive subscriptions
    // ----------------------------------------------------------

    const {
      data: subscriptions,
      error: subscriptionError,
    } = await supabase
      .from("company_subscriptions")
      .select("*")
      .eq("status", "inactive")
      .order("created_at", {
        ascending: false,
      })
      .limit(20);

    if (subscriptionError) {
      console.error(
        "Subscription lookup error:",
        subscriptionError
      );

      return new NextResponse(
        "Database error",
        { status: 500 }
      );
    }

    if (
      !subscriptions ||
      subscriptions.length === 0
    ) {
      console.error(
        "No inactive subscription found."
      );

      return new NextResponse(
        "Subscription not found",
        { status: 404 }
      );
    }

    // ----------------------------------------------------------
    // 9. Determine the plan from PayFast item name
    // ----------------------------------------------------------

    let planId = null;

    if (
      itemName &&
      itemName
        .toLowerCase()
        .includes("starter")
    ) {
      planId = "starter";
    }

    if (
      itemName &&
      itemName
        .toLowerCase()
        .includes("professional")
    ) {
      planId = "professional";
    }

    if (
      itemName &&
      itemName
        .toLowerCase()
        .includes("enterprise")
    ) {
      planId = "enterprise";
    }

    if (!planId) {
      console.error(
        "Could not identify GradLink plan."
      );

      return new NextResponse(
        "Plan not identified",
        { status: 400 }
      );
    }

    // ----------------------------------------------------------
    // 10. Find matching subscription
    // ----------------------------------------------------------

    const subscription =
      subscriptions.find(
        (item) => item.plan === planId
      );

    if (!subscription) {
      console.error(
        "Matching subscription not found."
      );

      return new NextResponse(
        "Matching subscription not found",
        { status: 404 }
      );
    }

    // ----------------------------------------------------------
    // 11. Prevent duplicate processing
    // ----------------------------------------------------------

    if (
      subscription.status?.toLowerCase() ===
      "active"
    ) {
      return new NextResponse("OK", {
        status: 200,
      });
    }

    // ----------------------------------------------------------
    // 12. Verify payment amount
    // ----------------------------------------------------------

    const paidAmount = Number(
      amountGross
    );

    const expectedMonthlyPrices = {
      starter: 500,
      professional: 950,
      enterprise: 1500,
    };

    const expectedMonthly =
      expectedMonthlyPrices[planId];

    const expectedMonthlyAmount =
      Number(expectedMonthly);

    const expectedAnnualAmount =
      Number(expectedMonthly * 10);

    const validAmount =
      paidAmount ===
        expectedMonthlyAmount ||
      paidAmount ===
        expectedAnnualAmount;

    if (!validAmount) {
      console.error(
        "Payment amount mismatch.",
        {
          planId,
          paidAmount,
          expectedMonthlyAmount,
          expectedAnnualAmount,
        }
      );

      return new NextResponse(
        "Invalid payment amount",
        { status: 400 }
      );
    }

    // ----------------------------------------------------------
    // 13. Activate subscription
    // ----------------------------------------------------------

    const { error: updateError } =
      await supabase
        .from("company_subscriptions")
        .update({
          status: "active",
          payment_provider: "payfast",
          payment_reference: paymentId,
          updated_at:
            new Date().toISOString(),
        })
        .eq("company_id", subscription.company_id)
        .eq("status", "inactive");

    if (updateError) {
      console.error(
        "Subscription activation error:",
        updateError
      );

      return new NextResponse(
        "Could not activate subscription",
        { status: 500 }
      );
    }

    console.log(
      "GradLink SA PayFast payment verified successfully.",
      {
        paymentId,
        planId,
        amount: paidAmount,
        email: emailAddress,
      }
    );

    // ----------------------------------------------------------
    // 14. Tell PayFast the notification was processed
    // ----------------------------------------------------------

    return new NextResponse("OK", {
      status: 200,
    });
  } catch (error) {
    console.error(
      "PayFast notification error:",
      error
    );

    return new NextResponse(
      "Server error",
      { status: 500 }
    );
  }
}
